export const dataBlog = {
  title: 'Làm việc với Terminal & Ubuntu',
  description:
    'Khóa học ReactJS từ cơ bản tới nâng cao, kết quả của khóa học này là bạn có thể làm hầu hết các dự án thường gặp với ReactJS. Cuối khóa học này bạn sẽ sở hữu một dự án giống Tiktok.com, bạn có thể tự tin đi xin việc khi nắm chắc các kiến thức được chia sẻ trong khóa học này.',
  thumb:
    'https://images.unsplash.com/photo-1555952678-f7e7bb98302d?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
  content: `<div class="_wrapper_fl251_1" style="--font-size: 1.6rem; --line-height: 1.8;"><p>Trong thời đại công nghệ số 4.0, việc học không còn bó buộc trong những cuốn sách truyền thống. Giờ đây, trí tuệ nhân tạo (AI) đang dần trở thành một trợ thủ đắc lực, giúp việc học trở nên hiệu quả và thú vị hơn. Một minh chứng rõ ràng cho sự chuyển mình này chính là câu chuyện của Hoàng Bảo Trung – một học viên ưu tú của F8, người đã đạt giải Nhì tại cuộc thi "Grand Final Of Best Web Design 2024" với dự án sáng tạo "AI Powered Learning".</p>
  <p><img alt="z5810974403863_16e55fab248a4f0d146f1dc9e33b18ca.jpg" src="https://files.fullstack.edu.vn/f8-prod/blog_posts/11503/66fd042a2c3bc.jpg" style="cursor: zoom-in;">
  <em>Bạn Hoàng Bảo Trung – Học viên của F8 đã đoạt giải Nhì cuộc thi "Grand Final Of Best Web Design 2024" với dự án sáng tạo "AI Powered Learning".</em></p>
  <p>Cuộc thi "Grand Final Of Best Web Design 2024" không chỉ đánh giá cao khả năng về công nghệ thiết kế mà còn yêu cầu kỹ năng lập trình web chuyên sâu. Trung và các thành viên trong nhóm đã gây ấn tượng mạnh mẽ với dự án mang tính đột phá: AI Powered Learning - một nền tảng học tập tích hợp chat và làm bài tập cùng AI. Dự án được hình thành từ chính sự thấu hiểu về nhu cầu học tập hiện đại – nơi mà học sinh, sinh viên không chỉ cần công cụ hỗ trợ học tập mà còn cần sự tương tác liên tục, không giới hạn thời gian.</p>
  <p><img alt="MG_0813.jpg" src="https://files.fullstack.edu.vn/f8-prod/blog_posts/11503/66fd03291e58f.jpg" style="cursor: zoom-in;">
  <em>Đội thi đã xuất sắc giành giải Nhì trong cuộc thi Grand Final of Best Web Design 2024.</em></p>
  <p>Khi được hỏi về ý tưởng thực hiện làm dự án Trung có chia sẻ: "<em>Dự án của nhóm mình tên là AI Powered Learning, đây là phần mềm tích hợp chat và làm bài tập cùng AI. Trang web này được tạo ra nhằm mục đích giúp các bạn học sinh và sinh viên có thể làm bài tập cùng AI, được AI chỉ dẫn như một người giáo viên thực thụ và luôn sẵn sàng giúp đỡ các bạn làm bài 24/7. Không chỉ dừng lại ở việc giúp các học sinh và sinh viên, AI Powered Learning còn giúp giáo viên ôn lại kiến thức cũ, tạo nên một môi trường học tập toàn diện và hiệu quả.</em>"</p>
  <p>Trong quá trình thực hiện dự án "AI Powered Learning" Trung và nhóm đã gặp phải không ít khó khăn, đặc biệt ở phần Frontend. Đây là một thách thức lớn khi thế mạnh của Trung ban đầu là lập trình C#, một ngôn ngữ chủ yếu dùng cho Backend. Tuy nhiên, nhờ những kiến thức và kỹ năng tích lũy từ các khóa học của F8, bạn đã nhanh chóng làm chủ được phần Frontend. Trung chia sẻ: "<em>Mình xuất thân là học C# nhưng nhờ học các khóa F8 mà giờ mình có thể làm tốt được Frontend và được mọi người đánh giá rất cao, minh chứng là các danh hiệu ở các cuộc thi mà mình đã đạt được.</em>"</p>
  <p>Khi được hỏi về lý do chọn F8 để phát triển kỹ năng của mình, Trung nhấn mạnh: "<em>Mình lựa chọn F8 vì F8 dạy cực kỳ chuyên nghiệp, có lộ trình rõ ràng. Cách truyền đạt lý thuyết và thực hành rất hay, và anh Sơn giảng bài làm mình thấy cuốn hút.</em>" Chính phương pháp học hiện đại và cách giảng dạy truyền cảm hứng từ đội ngũ F8 đã giúp Trung và nhóm rất nhiều trong quá trình tham gia cuộc thi.</p>
  <p>Dù chỉ có 7 ngày để hoàn thiện dự án, nhóm đã phải làm việc không ngừng nghỉ. Từ việc xây dựng sitemap, thiết kế giao diện đến thay đổi theme tới ba lần, tất cả đã diễn ra dưới áp lực thời gian gấp gáp. Dù phải thức đêm liên tục và khung thời gian khá hạn hẹp vì nhóm vẫn phải đi thực tập, nhưng những khó khăn ấy không thể làm mất đi tinh thần quyết tâm của cả nhóm. Trung hồi tưởng: "<em>Chúng mình đã mất 2 ngày đầu để lên sitemap và thiết kế giao diện, sau đó thay đổi tới 3 lần theme trước khi chọn được giao diện phù hợp. Dù phải thức đêm liên tục và thời gian khá gấp rút vì nhóm vẫn phải đi thực tập, nhưng nhờ đó, chúng mình đã có những kỷ niệm rất đẹp khi cùng ăn, cùng ngủ và cùng code với nhau.</em>"</p>
  <p><img alt="z5823859745812_4257440667065c855d8afa2cd50002e9.jpg" src="https://files.fullstack.edu.vn/f8-prod/blog_posts/11503/66fd0383b78ab.jpg" style="cursor: zoom-in;">
  <em>Bảng vinh danh giải thưởng giải Nhì trong cuộc thi Grand Final of Best Web Design 2024.</em></p>
  <p>Chính từ những thử thách ấy, nhóm đã học được cách làm việc nhóm hiệu quả, vượt qua khó khăn và tiến bộ hơn từng ngày. Không chỉ dừng lại ở đây, những kinh nghiệm từ việc phải giải quyết các vấn đề về giao diện và hiệu suất trong thời gian ngắn sẽ là hành trang quý giá cho các thành viên của nhóm trong tương lai.</p>
  <p>Khi nói về những dự định sắp tới, Trung mong muốn tiếp tục phát triển bản thân trong lĩnh vực lập trình, bởi bạn hiểu rằng: "<em>Trong ngành lập trình, nếu mình không liên tục học hỏi, mình sẽ nhanh chóng bị tụt hậu.</em>" Điều này thôi thúc Trung không ngừng cố gắng và nỗ lực. Ước mơ lớn nhất của bạn là được ra Hà Nội và gia nhập đội ngũ F8 – nơi đã truyền cho bạn niềm cảm hứng mạnh mẽ trong suốt quá trình học tập và làm việc.</p>
  </div>`,
};
